// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.14.0
// source: model/Messages.proto

package model

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Ack struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Ack) Reset() {
	*x = Ack{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_Messages_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_model_Messages_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_model_Messages_proto_rawDescGZIP(), []int{0}
}

type Error struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *Error) Reset() {
	*x = Error{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_Messages_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_model_Messages_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_model_Messages_proto_rawDescGZIP(), []int{1}
}

func (x *Error) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Error) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type Address struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID   []byte `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	DeviceID uint32 `protobuf:"varint,2,opt,name=deviceID,proto3" json:"deviceID,omitempty"`
}

func (x *Address) Reset() {
	*x = Address{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_Messages_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_model_Messages_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_model_Messages_proto_rawDescGZIP(), []int{2}
}

func (x *Address) GetUserID() []byte {
	if x != nil {
		return x.UserID
	}
	return nil
}

func (x *Address) GetDeviceID() uint32 {
	if x != nil {
		return x.DeviceID
	}
	return 0
}

type Login struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address   *Address `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Signature []byte   `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (x *Login) Reset() {
	*x = Login{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_Messages_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Login) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Login) ProtoMessage() {}

func (x *Login) ProtoReflect() protoreflect.Message {
	mi := &file_model_Messages_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Login.ProtoReflect.Descriptor instead.
func (*Login) Descriptor() ([]byte, []int) {
	return file_model_Messages_proto_rawDescGZIP(), []int{3}
}

func (x *Login) GetAddress() *Address {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *Login) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

type Register struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RegistrationID uint32   `protobuf:"varint,1,opt,name=registrationID,proto3" json:"registrationID,omitempty"`
	SignedPreKey   []byte   `protobuf:"bytes,2,opt,name=signedPreKey,proto3" json:"signedPreKey,omitempty"`
	PreKeys        [][]byte `protobuf:"bytes,3,rep,name=preKeys,proto3" json:"preKeys,omitempty"`
}

func (x *Register) Reset() {
	*x = Register{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_Messages_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Register) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Register) ProtoMessage() {}

func (x *Register) ProtoReflect() protoreflect.Message {
	mi := &file_model_Messages_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Register.ProtoReflect.Descriptor instead.
func (*Register) Descriptor() ([]byte, []int) {
	return file_model_Messages_proto_rawDescGZIP(), []int{4}
}

func (x *Register) GetRegistrationID() uint32 {
	if x != nil {
		return x.RegistrationID
	}
	return 0
}

func (x *Register) GetSignedPreKey() []byte {
	if x != nil {
		return x.SignedPreKey
	}
	return nil
}

func (x *Register) GetPreKeys() [][]byte {
	if x != nil {
		return x.PreKeys
	}
	return nil
}

type Unregister struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Unregister) Reset() {
	*x = Unregister{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_Messages_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Unregister) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Unregister) ProtoMessage() {}

func (x *Unregister) ProtoReflect() protoreflect.Message {
	mi := &file_model_Messages_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Unregister.ProtoReflect.Descriptor instead.
func (*Unregister) Descriptor() ([]byte, []int) {
	return file_model_Messages_proto_rawDescGZIP(), []int{5}
}

type RequestPreKeys struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID         []byte   `protobuf:"bytes,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	KnownDeviceIDs []uint32 `protobuf:"varint,2,rep,packed,name=knownDeviceIDs,proto3" json:"knownDeviceIDs,omitempty"`
}

func (x *RequestPreKeys) Reset() {
	*x = RequestPreKeys{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_Messages_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestPreKeys) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestPreKeys) ProtoMessage() {}

func (x *RequestPreKeys) ProtoReflect() protoreflect.Message {
	mi := &file_model_Messages_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestPreKeys.ProtoReflect.Descriptor instead.
func (*RequestPreKeys) Descriptor() ([]byte, []int) {
	return file_model_Messages_proto_rawDescGZIP(), []int{6}
}

func (x *RequestPreKeys) GetUserID() []byte {
	if x != nil {
		return x.UserID
	}
	return nil
}

func (x *RequestPreKeys) GetKnownDeviceIDs() []uint32 {
	if x != nil {
		return x.KnownDeviceIDs
	}
	return nil
}

type PreKey struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID         []byte `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	DeviceID       uint32 `protobuf:"varint,2,opt,name=deviceID,proto3" json:"deviceID,omitempty"`
	RegistrationID uint32 `protobuf:"varint,3,opt,name=registrationID,proto3" json:"registrationID,omitempty"`
	SignedPreKey   []byte `protobuf:"bytes,4,opt,name=signedPreKey,proto3" json:"signedPreKey,omitempty"`
	PreKey         []byte `protobuf:"bytes,5,opt,name=preKey,proto3" json:"preKey,omitempty"`
}

func (x *PreKey) Reset() {
	*x = PreKey{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_Messages_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PreKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreKey) ProtoMessage() {}

func (x *PreKey) ProtoReflect() protoreflect.Message {
	mi := &file_model_Messages_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreKey.ProtoReflect.Descriptor instead.
func (*PreKey) Descriptor() ([]byte, []int) {
	return file_model_Messages_proto_rawDescGZIP(), []int{7}
}

func (x *PreKey) GetUserID() []byte {
	if x != nil {
		return x.UserID
	}
	return nil
}

func (x *PreKey) GetDeviceID() uint32 {
	if x != nil {
		return x.DeviceID
	}
	return 0
}

func (x *PreKey) GetRegistrationID() uint32 {
	if x != nil {
		return x.RegistrationID
	}
	return 0
}

func (x *PreKey) GetSignedPreKey() []byte {
	if x != nil {
		return x.SignedPreKey
	}
	return nil
}

func (x *PreKey) GetPreKey() []byte {
	if x != nil {
		return x.PreKey
	}
	return nil
}

type PreKeysLow struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	KeysRequested uint32 `protobuf:"varint,1,opt,name=keysRequested,proto3" json:"keysRequested,omitempty"`
}

func (x *PreKeysLow) Reset() {
	*x = PreKeysLow{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_Messages_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PreKeysLow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreKeysLow) ProtoMessage() {}

func (x *PreKeysLow) ProtoReflect() protoreflect.Message {
	mi := &file_model_Messages_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreKeysLow.ProtoReflect.Descriptor instead.
func (*PreKeysLow) Descriptor() ([]byte, []int) {
	return file_model_Messages_proto_rawDescGZIP(), []int{8}
}

func (x *PreKeysLow) GetKeysRequested() uint32 {
	if x != nil {
		return x.KeysRequested
	}
	return 0
}

type OutboundMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	To                        *Address `protobuf:"bytes,1,opt,name=to,proto3" json:"to,omitempty"`
	UnidentifiedSenderMessage []byte   `protobuf:"bytes,2,opt,name=unidentifiedSenderMessage,proto3" json:"unidentifiedSenderMessage,omitempty"`
}

func (x *OutboundMessage) Reset() {
	*x = OutboundMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_Messages_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OutboundMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutboundMessage) ProtoMessage() {}

func (x *OutboundMessage) ProtoReflect() protoreflect.Message {
	mi := &file_model_Messages_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutboundMessage.ProtoReflect.Descriptor instead.
func (*OutboundMessage) Descriptor() ([]byte, []int) {
	return file_model_Messages_proto_rawDescGZIP(), []int{9}
}

func (x *OutboundMessage) GetTo() *Address {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *OutboundMessage) GetUnidentifiedSenderMessage() []byte {
	if x != nil {
		return x.UnidentifiedSenderMessage
	}
	return nil
}

type Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sequence uint32 `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	// Types that are assignable to Payload:
	//	*Message_Ack
	//	*Message_Error
	//	*Message_Login
	//	*Message_Register
	//	*Message_Unregister
	//	*Message_RequestPreKeys
	//	*Message_PreKey
	//	*Message_PreKeysLow
	//	*Message_OutboundMessage
	//	*Message_InboundMessage
	Payload isMessage_Payload `protobuf_oneof:"payload"`
}

func (x *Message) Reset() {
	*x = Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_model_Messages_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_model_Messages_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_model_Messages_proto_rawDescGZIP(), []int{10}
}

func (x *Message) GetSequence() uint32 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (m *Message) GetPayload() isMessage_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (x *Message) GetAck() *Ack {
	if x, ok := x.GetPayload().(*Message_Ack); ok {
		return x.Ack
	}
	return nil
}

func (x *Message) GetError() *Error {
	if x, ok := x.GetPayload().(*Message_Error); ok {
		return x.Error
	}
	return nil
}

func (x *Message) GetLogin() *Login {
	if x, ok := x.GetPayload().(*Message_Login); ok {
		return x.Login
	}
	return nil
}

func (x *Message) GetRegister() *Register {
	if x, ok := x.GetPayload().(*Message_Register); ok {
		return x.Register
	}
	return nil
}

func (x *Message) GetUnregister() *Unregister {
	if x, ok := x.GetPayload().(*Message_Unregister); ok {
		return x.Unregister
	}
	return nil
}

func (x *Message) GetRequestPreKeys() *RequestPreKeys {
	if x, ok := x.GetPayload().(*Message_RequestPreKeys); ok {
		return x.RequestPreKeys
	}
	return nil
}

func (x *Message) GetPreKey() *PreKey {
	if x, ok := x.GetPayload().(*Message_PreKey); ok {
		return x.PreKey
	}
	return nil
}

func (x *Message) GetPreKeysLow() *PreKeysLow {
	if x, ok := x.GetPayload().(*Message_PreKeysLow); ok {
		return x.PreKeysLow
	}
	return nil
}

func (x *Message) GetOutboundMessage() *OutboundMessage {
	if x, ok := x.GetPayload().(*Message_OutboundMessage); ok {
		return x.OutboundMessage
	}
	return nil
}

func (x *Message) GetInboundMessage() []byte {
	if x, ok := x.GetPayload().(*Message_InboundMessage); ok {
		return x.InboundMessage
	}
	return nil
}

type isMessage_Payload interface {
	isMessage_Payload()
}

type Message_Ack struct {
	Ack *Ack `protobuf:"bytes,2,opt,name=ack,proto3,oneof"`
}

type Message_Error struct {
	Error *Error `protobuf:"bytes,3,opt,name=error,proto3,oneof"`
}

type Message_Login struct {
	Login *Login `protobuf:"bytes,4,opt,name=login,proto3,oneof"`
}

type Message_Register struct {
	Register *Register `protobuf:"bytes,5,opt,name=register,proto3,oneof"`
}

type Message_Unregister struct {
	Unregister *Unregister `protobuf:"bytes,6,opt,name=unregister,proto3,oneof"`
}

type Message_RequestPreKeys struct {
	RequestPreKeys *RequestPreKeys `protobuf:"bytes,7,opt,name=requestPreKeys,proto3,oneof"`
}

type Message_PreKey struct {
	PreKey *PreKey `protobuf:"bytes,8,opt,name=preKey,proto3,oneof"`
}

type Message_PreKeysLow struct {
	PreKeysLow *PreKeysLow `protobuf:"bytes,9,opt,name=preKeysLow,proto3,oneof"`
}

type Message_OutboundMessage struct {
	OutboundMessage *OutboundMessage `protobuf:"bytes,10,opt,name=outboundMessage,proto3,oneof"`
}

type Message_InboundMessage struct {
	InboundMessage []byte `protobuf:"bytes,11,opt,name=inboundMessage,proto3,oneof"`
}

func (*Message_Ack) isMessage_Payload() {}

func (*Message_Error) isMessage_Payload() {}

func (*Message_Login) isMessage_Payload() {}

func (*Message_Register) isMessage_Payload() {}

func (*Message_Unregister) isMessage_Payload() {}

func (*Message_RequestPreKeys) isMessage_Payload() {}

func (*Message_PreKey) isMessage_Payload() {}

func (*Message_PreKeysLow) isMessage_Payload() {}

func (*Message_OutboundMessage) isMessage_Payload() {}

func (*Message_InboundMessage) isMessage_Payload() {}

var File_model_Messages_proto protoreflect.FileDescriptor

var file_model_Messages_proto_rawDesc = []byte{
	0x0a, 0x14, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2f, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x22, 0x05,
	0x0a, 0x03, 0x41, 0x63, 0x6b, 0x22, 0x3d, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x22, 0x3d, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12,
	0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x64, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x49, 0x44, 0x22, 0x50, 0x0a, 0x05, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x29, 0x0a, 0x07,
	0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e,
	0x73, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x2e, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x07,
	0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61,
	0x74, 0x75, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x73, 0x69, 0x67, 0x6e,
	0x61, 0x74, 0x75, 0x72, 0x65, 0x22, 0x70, 0x0a, 0x08, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65,
	0x72, 0x12, 0x26, 0x0a, 0x0e, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0e, 0x72, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x12, 0x22, 0x0a, 0x0c, 0x73, 0x69, 0x67,
	0x6e, 0x65, 0x64, 0x50, 0x72, 0x65, 0x4b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x0c, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x50, 0x72, 0x65, 0x4b, 0x65, 0x79, 0x12, 0x18, 0x0a,
	0x07, 0x70, 0x72, 0x65, 0x4b, 0x65, 0x79, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x07,
	0x70, 0x72, 0x65, 0x4b, 0x65, 0x79, 0x73, 0x22, 0x0c, 0x0a, 0x0a, 0x55, 0x6e, 0x72, 0x65, 0x67,
	0x69, 0x73, 0x74, 0x65, 0x72, 0x22, 0x50, 0x0a, 0x0e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x50, 0x72, 0x65, 0x4b, 0x65, 0x79, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49,
	0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12,
	0x26, 0x0a, 0x0e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x44, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x44,
	0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0d, 0x52, 0x0e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x44, 0x65,
	0x76, 0x69, 0x63, 0x65, 0x49, 0x44, 0x73, 0x22, 0xa0, 0x01, 0x0a, 0x06, 0x50, 0x72, 0x65, 0x4b,
	0x65, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x65,
	0x76, 0x69, 0x63, 0x65, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x64, 0x65,
	0x76, 0x69, 0x63, 0x65, 0x49, 0x44, 0x12, 0x26, 0x0a, 0x0e, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0e,
	0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x12, 0x22,
	0x0a, 0x0c, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x50, 0x72, 0x65, 0x4b, 0x65, 0x79, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x0c, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x50, 0x72, 0x65, 0x4b,
	0x65, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x72, 0x65, 0x4b, 0x65, 0x79, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x06, 0x70, 0x72, 0x65, 0x4b, 0x65, 0x79, 0x22, 0x32, 0x0a, 0x0a, 0x50, 0x72,
	0x65, 0x4b, 0x65, 0x79, 0x73, 0x4c, 0x6f, 0x77, 0x12, 0x24, 0x0a, 0x0d, 0x6b, 0x65, 0x79, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x0d, 0x6b, 0x65, 0x79, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65, 0x64, 0x22, 0x70,
	0x0a, 0x0f, 0x4f, 0x75, 0x74, 0x62, 0x6f, 0x75, 0x6e, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x12, 0x1f, 0x0a, 0x02, 0x74, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e,
	0x73, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x2e, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x02,
	0x74, 0x6f, 0x12, 0x3c, 0x0a, 0x19, 0x75, 0x6e, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x69,
	0x65, 0x64, 0x53, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x19, 0x75, 0x6e, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66,
	0x69, 0x65, 0x64, 0x53, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x22, 0x96, 0x04, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08,
	0x73, 0x65, 0x71, 0x75, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x1f, 0x0a, 0x03, 0x61, 0x63, 0x6b, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x2e, 0x41,
	0x63, 0x6b, 0x48, 0x00, 0x52, 0x03, 0x61, 0x63, 0x6b, 0x12, 0x25, 0x0a, 0x05, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x73, 0x69, 0x67, 0x6e, 0x61,
	0x6c, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x48, 0x00, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x12, 0x25, 0x0a, 0x05, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0d, 0x2e, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x48, 0x00,
	0x52, 0x05, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x12, 0x2e, 0x0a, 0x08, 0x72, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x73, 0x69, 0x67, 0x6e,
	0x61, 0x6c, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x48, 0x00, 0x52, 0x08, 0x72,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x12, 0x34, 0x0a, 0x0a, 0x75, 0x6e, 0x72, 0x65, 0x67,
	0x69, 0x73, 0x74, 0x65, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x73, 0x69,
	0x67, 0x6e, 0x61, 0x6c, 0x2e, 0x55, 0x6e, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x48,
	0x00, 0x52, 0x0a, 0x75, 0x6e, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x12, 0x40, 0x0a,
	0x0e, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x72, 0x65, 0x4b, 0x65, 0x79, 0x73, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x2e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x72, 0x65, 0x4b, 0x65, 0x79, 0x73, 0x48, 0x00, 0x52,
	0x0e, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x72, 0x65, 0x4b, 0x65, 0x79, 0x73, 0x12,
	0x28, 0x0a, 0x06, 0x70, 0x72, 0x65, 0x4b, 0x65, 0x79, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0e, 0x2e, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x2e, 0x50, 0x72, 0x65, 0x4b, 0x65, 0x79, 0x48,
	0x00, 0x52, 0x06, 0x70, 0x72, 0x65, 0x4b, 0x65, 0x79, 0x12, 0x34, 0x0a, 0x0a, 0x70, 0x72, 0x65,
	0x4b, 0x65, 0x79, 0x73, 0x4c, 0x6f, 0x77, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e,
	0x73, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x2e, 0x50, 0x72, 0x65, 0x4b, 0x65, 0x79, 0x73, 0x4c, 0x6f,
	0x77, 0x48, 0x00, 0x52, 0x0a, 0x70, 0x72, 0x65, 0x4b, 0x65, 0x79, 0x73, 0x4c, 0x6f, 0x77, 0x12,
	0x43, 0x0a, 0x0f, 0x6f, 0x75, 0x74, 0x62, 0x6f, 0x75, 0x6e, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x73, 0x69, 0x67, 0x6e, 0x61,
	0x6c, 0x2e, 0x4f, 0x75, 0x74, 0x62, 0x6f, 0x75, 0x6e, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x48, 0x00, 0x52, 0x0f, 0x6f, 0x75, 0x74, 0x62, 0x6f, 0x75, 0x6e, 0x64, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x12, 0x28, 0x0a, 0x0e, 0x69, 0x6e, 0x62, 0x6f, 0x75, 0x6e, 0x64, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0c, 0x48, 0x00, 0x52, 0x0e,
	0x69, 0x6e, 0x62, 0x6f, 0x75, 0x6e, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x42, 0x09,
	0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x42, 0x2e, 0x5a, 0x2c, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x67, 0x65, 0x74, 0x6c, 0x61, 0x6e, 0x74, 0x65,
	0x72, 0x6e, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x2d, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_model_Messages_proto_rawDescOnce sync.Once
	file_model_Messages_proto_rawDescData = file_model_Messages_proto_rawDesc
)

func file_model_Messages_proto_rawDescGZIP() []byte {
	file_model_Messages_proto_rawDescOnce.Do(func() {
		file_model_Messages_proto_rawDescData = protoimpl.X.CompressGZIP(file_model_Messages_proto_rawDescData)
	})
	return file_model_Messages_proto_rawDescData
}

var file_model_Messages_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_model_Messages_proto_goTypes = []interface{}{
	(*Ack)(nil),             // 0: signal.Ack
	(*Error)(nil),           // 1: signal.Error
	(*Address)(nil),         // 2: signal.Address
	(*Login)(nil),           // 3: signal.Login
	(*Register)(nil),        // 4: signal.Register
	(*Unregister)(nil),      // 5: signal.Unregister
	(*RequestPreKeys)(nil),  // 6: signal.RequestPreKeys
	(*PreKey)(nil),          // 7: signal.PreKey
	(*PreKeysLow)(nil),      // 8: signal.PreKeysLow
	(*OutboundMessage)(nil), // 9: signal.OutboundMessage
	(*Message)(nil),         // 10: signal.Message
}
var file_model_Messages_proto_depIdxs = []int32{
	2,  // 0: signal.Login.address:type_name -> signal.Address
	2,  // 1: signal.OutboundMessage.to:type_name -> signal.Address
	0,  // 2: signal.Message.ack:type_name -> signal.Ack
	1,  // 3: signal.Message.error:type_name -> signal.Error
	3,  // 4: signal.Message.login:type_name -> signal.Login
	4,  // 5: signal.Message.register:type_name -> signal.Register
	5,  // 6: signal.Message.unregister:type_name -> signal.Unregister
	6,  // 7: signal.Message.requestPreKeys:type_name -> signal.RequestPreKeys
	7,  // 8: signal.Message.preKey:type_name -> signal.PreKey
	8,  // 9: signal.Message.preKeysLow:type_name -> signal.PreKeysLow
	9,  // 10: signal.Message.outboundMessage:type_name -> signal.OutboundMessage
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_model_Messages_proto_init() }
func file_model_Messages_proto_init() {
	if File_model_Messages_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_model_Messages_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ack); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_Messages_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Error); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_Messages_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Address); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_Messages_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Login); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_Messages_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Register); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_Messages_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Unregister); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_Messages_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestPreKeys); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_Messages_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PreKey); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_Messages_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PreKeysLow); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_Messages_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OutboundMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_model_Messages_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_model_Messages_proto_msgTypes[10].OneofWrappers = []interface{}{
		(*Message_Ack)(nil),
		(*Message_Error)(nil),
		(*Message_Login)(nil),
		(*Message_Register)(nil),
		(*Message_Unregister)(nil),
		(*Message_RequestPreKeys)(nil),
		(*Message_PreKey)(nil),
		(*Message_PreKeysLow)(nil),
		(*Message_OutboundMessage)(nil),
		(*Message_InboundMessage)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_model_Messages_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_model_Messages_proto_goTypes,
		DependencyIndexes: file_model_Messages_proto_depIdxs,
		MessageInfos:      file_model_Messages_proto_msgTypes,
	}.Build()
	File_model_Messages_proto = out.File
	file_model_Messages_proto_rawDesc = nil
	file_model_Messages_proto_goTypes = nil
	file_model_Messages_proto_depIdxs = nil
}
