name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - name: Start Redis
      uses: supercharge/redis-github-action@1.1.0
      with:
        redis-version: 6.2-rc3
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15.x
    - name: Install build tools if necessary (for running locally with act)
      run: command -v make 2>&1 || DEBIAN_FRONTEND=noninteractive sudo apt update && sudo apt install -y build-essential
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test
      run: make test-and-cover
    - name: Fetch Goveralls
      run: go get github.com/mattn/goveralls
    - name: Upload Coverage
      env:
        COVERALLS_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
      run: make upload-coverage